### ISSUE TITLE
This is dysfunctional.

### ISSUE THREAD

**Issue by imdevine** [seruva19/kubin#122]
Step 1: Upon completion of all steps and proceeding to use Gradio:
Running on local URL:  http://127.0.0.1:7860/
Running on public URL: https://5267e59a6cc5ceed42.gradio.live/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)

Step 2: The following procedures start to take place:

scanning system information

task queued: text2img
prior/diffusion_pytorch_model.safetensors not found
Loading pipeline components...: 100% 6/6 [00:47<00:00,  7.89s/it]
following pipelines, if active, will be released for text2img task: ['text2img_cnet', 'inpainting']
Downloading (…)ain/unet/config.json: 100% 1.67k/1.67k [00:00<00:00, 7.52MB/s]
Downloading (…)on_pytorch_model.bin: 100% 5.01G/5.01G [02:20<00:00, 35.7MB/s]

Step 3: After downloading and installing the dependencies from the Step 2 (which doesn't always happen, most of the time the process freezes at some step), Gradio throws "connection errored out" and stops working.

**Comment by seruva19** [comment]
Are you using colab?

**Comment by imdevine** [comment]
Sometimes it works, most of the time it doesn't. It looks like the repository tries to achieve multiple things at the same time, without making sure that the basic functionality works.
Focus on making sure that running this code from start to finish results in a functional text2img, img2img, inpainting, etc, in that order, without optimizations, without gradio, etc.
All these blows and whistles don't matter because the underlying functionality doesn't work.

**Comment by imdevine** [comment]
> Are you using colab?

Tried in colab, same problems.

**Comment by seruva19** [comment]
Sorry, I was not able to reproduce your error (tried fresh install as well).
I can only suppose that it requires a lot of time to load models at first launch, and gradio app disconnects because of timeout. But that never happened to me (when working locally).

If this app does not work for you as expected, I recommend to pay attention to other ways to use Kandinsky locally mentioned here: https://github.com/seruva19/kubin/wiki/Docs#alternative-solutions

**Comment by imdevine** [comment]
>I can only suppose that it requires a lot of time to load models at first launch, and gradio app disconnects because of timeout. 
Loading models prior to running Gradio would solve the problem. Why do you do it upon the first image generation instead of preloading the models in advance?

**Comment by seruva19** [comment]
I understand your point, but my approach is different: download of models is initiated only after user explicitly requests it (by pressing text2img button or whatever), only then required components are fetched, and no preload should happen before app UI itself is loaded.
On next launch downloaded components will be called from disk cache. And maybe the user doesn't want to download models, maybe they are about to open image browser or do some training, or want to use 2.1 model instead of "default" 2.2, etc.
