### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by tushengzhang** [seruva19/kubin#8]
RuntimeError: Expected is_sm90 || is_sm8x || is_sm75 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

**Comment by seruva19** [comment]
This error might happen, if you launch with "--use-flash-attention" flag on GPU that does not support Flash Attention (see https://github.com/lm-sys/FastChat/issues/498). You can read about supported devices [here](https://github.com/HazyResearch/flash-attention#installation-and-features),

> FlashAttention currently supports:
> Turing, Ampere, Ada, or Hopper GPUs (e.g., H100, A100, RTX 3090, T4, RTX 2080).

I only tested it on T4, A100, RTX5000 and A4000. 

So either do not apply "--use-flash-attention" or (if you are getting this error while using precompiled wheels from this repo) try to compile Flash Attention from source on your own, because these wheels are only targeting cloud environments (Google Colab, Paperspace and Kaggle) with specific versions of Python & PyTorch.

**Comment by tushengzhang** [comment]
Thank you very much, I'm using a p4000, 8g, maybe this graphics card is not very good, for me as a person who does not know how to code, it is too difficult to solve these, I'll use it later when I have a chance.

**Comment by seruva19** [comment]
P4000 is not bad card (it's similar to Tesla T4 and even slightly better), but Kandinsky uses > 9 Gb of VRAM for generating 512x512 images. When we find a way to lower it below 8 Gb, P4000 wil work fine.

**Comment by tushengzhang** [comment]
Thank you very much.
